---
- hosts: kanboard
  vars:
    ansible_python_interpreter: /usr/bin/python3
    kanboard_version: 1.2.21
    previous_version: 1.2.20
  tasks:

  #################################
  ## setup the user, the domain, the database
  #################################
  - name: ensure user exists
    hsuser.js: name="{{pac}}-{{user}}" password="{{password}}" exists="true"
  - name: setup domain
    hsdomain.js: name="{{domain}}" owner="{{pac}}-{{user}}" exists="true"
  - name: setup database
    hsdatabase.js: name="{{pac}}_{{user}}" password="{{password}}" instance="postgresql" exists="true"


  #################################
  ## install kanboard
  #################################
  - name: install kanboard
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}
      src: https://github.com/kanboard/kanboard/archive/refs/tags/v{{kanboard_version}}.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}

  #################################
  ## install data directory
  #################################
  - name: Check for HDD storage
    stat:
      path: /home/storage/{{pac}}/users/{{user}}
    register: hdd_storage
  - name: create data directory on storage
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/storage/{{pac}}/users/{{user}}/data"
      state: directory
      mode: 0744
    when: hdd_storage.stat.exists

  - name: create symbolic link for data to storage
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/storage/{{pac}}/users/{{user}}/data"
      dest: "/home/pacs/{{pac}}/users/{{user}}/data"
      state: link
    when: hdd_storage.stat.exists

  - name: create data directory on sdd
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/data"
      state: directory
      mode: 0744
    when: not hdd_storage.stat.exists

  - name: upload apache .htaccess to data directory
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/data/.htaccess" src="templates/htaccess" mode=0644

  #################################
  ## prepare configuration file
  #################################
  - name: copy config file
    become: yes
    become_user: "{{pac}}-{{user}}"
    copy:
      src: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.default.php"
      remote_src: yes
      dest: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
  - name: set db driver
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''DB_DRIVER'','
      line: "define('DB_DRIVER', 'postgres');"
  - name: set db name
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''DB_NAME'','
      line: "define('DB_NAME', '{{pac}}_{{user}}');"
  - name: set db user name
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''DB_USERNAME'','
      line: "define('DB_USERNAME', '{{pac}}_{{user}}' );"
  - name: set database password
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''DB_PASSWORD'','
      line: "define('DB_PASSWORD', '{{password}}' );"

  - name: set data directory path
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''DATA_DIR'','
      line: "define('DATA_DIR', '/home/pacs/{{pac}}/users/{{user}}/data' );"

  #################################
  ## configure email
  #################################
  - name: set mail method
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''MAIL_TRANSPORT'','
      line: "define('MAIL_TRANSPORT', 'smtp' );"

  - name: set mail from
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''MAIL_FROM'','
      line: "define('MAIL_FROM', '{{mail_from}}' );"

  - name: set smtp hostname
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''MAIL_SMTP_HOSTNAME'','
      line: "define('MAIL_SMTP_HOSTNAME', '{{mail_hostname}}' );"

  - name: set smtp port
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''MAIL_SMTP_PORT'','
      line: "define('MAIL_SMTP_PORT', 587);"

  - name: set smtp encryption
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''MAIL_SMTP_ENCRYPTION'','
      line: "define('MAIL_SMTP_ENCRYPTION', 'tls');"

  - name: set smtp username
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''MAIL_SMTP_USERNAME'','
      line: "define('MAIL_SMTP_USERNAME', '{{mail_username}}' );"

  - name: set smtp password
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/config.php"
      regexp: '^define\(''MAIL_SMTP_PASSWORD'','
      line: "define('MAIL_SMTP_PASSWORD', '{{mail_password}}' );"

  #################################
  ## prepare for SAAS environment
  #################################
  - name: deactivate admin user
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/app/Schema/Postgres.php"
      regexp: '^    $pdo->exec\("UPDATE users SET is_active = false'
      insertafter: '.*ALTER TABLE "projects" ADD COLUMN enable_global_tags.*'
      line: '    $pdo->exec("UPDATE users SET is_active = false WHERE username=''admin'' and email IS NULL;");'
    when: SaasEnvironment

  - name: upload activation script
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}/saasadmin.php" src="templates/saasadmin.php" mode=0644
    when: SaasEnvironment

  #################################
  ## activate website
  #################################
  - name: drop htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
       state: absent

  - name: create symbolic link for htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{kanboard_version}}"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
      state: link

  #################################
  ## remove old version of kanboard
  #################################
  - name: drop old installation
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/kanboard-{{previous_version}}"
       state: absent
