---
- hosts: kanboard
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  #################################
  ## setup the user, the domain, the database
  #################################
  - name: ensure user exists
    hsuser.js: name="{{pac}}-{{user}}" password="{{password}}" exists="true"
  - name: setup domain
    hsdomain.js: name="{{domain}}" owner="{{pac}}-{{user}}" exists="true"
  - name: setup database
    hsdatabase.js: name="{{pac}}_{{user}}" password="{{password}}" instance="{{dbms}}" exists="true"
  - name: Sleep to avoid issue invalid user for temporary files
    pause:
      seconds: 10

  #################################
  ## install kanboard
  #################################
  - name: create kanboard directory
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard"
      state: directory
      mode: 0755

  - name: install kanboard
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/kanboard/config.default.php
      src: https://github.com/kanboard/kanboard/archive/refs/tags/v{{kanboard_version}}.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/kanboard
      extra_opts: [--strip-components=1]

  - name: upload apache .htaccess to domain directory for API access
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/.htaccess" src="templates/htaccess_domain" mode=0644

  #################################
  ## install data directory
  #################################
  - name: Check for HDD storage
    stat:
      path: /home/storage/{{pac}}/users/{{user}}
    register: hdd_storage
  - name: create data directory on storage
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/storage/{{pac}}/users/{{user}}/data"
      state: directory
      mode: 0744
    when: hdd_storage.stat.exists

  - name: create symbolic link for data to storage
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/storage/{{pac}}/users/{{user}}/data"
      dest: "/home/pacs/{{pac}}/users/{{user}}/data"
      state: link
    when: hdd_storage.stat.exists

  - name: create data directory on ssd
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/data"
      state: directory
      mode: 0744
    when: not hdd_storage.stat.exists

  - name: upload apache .htaccess to data directory
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/data/.htaccess" src="templates/htaccess" mode=0644

  #################################
  ## prepare configuration file
  #################################
  - name: copy config file
    become: yes
    become_user: "{{pac}}-{{user}}"
    copy:
      src: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.default.php"
      remote_src: yes
      dest: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"

  - name: set db driver for postgresql
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''DB_DRIVER'','
      line: "define('DB_DRIVER', 'postgres');"
    when: dbms == "postgresql"

  - name: set db driver for mysql
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''DB_DRIVER'','
      line: "define('DB_DRIVER', 'mysql');"
    when: dbms == "mysql"

  - name: set db name
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''DB_NAME'','
      line: "define('DB_NAME', '{{pac}}_{{user}}');"
  - name: set db user name
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''DB_USERNAME'','
      line: "define('DB_USERNAME', '{{pac}}_{{user}}' );"
  - name: set database password
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''DB_PASSWORD'','
      line: "define('DB_PASSWORD', '{{password}}' );"

  - name: set data directory path
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''DATA_DIR'','
      line: "define('DATA_DIR', '/home/pacs/{{pac}}/users/{{user}}/data' );"

  #################################
  ## configure email
  #################################
  - name: set mail method
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''MAIL_TRANSPORT'','
      line: "define('MAIL_TRANSPORT', 'smtp' );"

  - name: set mail from
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''MAIL_FROM'','
      line: "define('MAIL_FROM', '{{mail_from}}' );"

  - name: set smtp hostname
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''MAIL_SMTP_HOSTNAME'','
      line: "define('MAIL_SMTP_HOSTNAME', '{{mail_hostname}}' );"

  - name: set smtp port
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''MAIL_SMTP_PORT'','
      line: "define('MAIL_SMTP_PORT', 587);"

  - name: set smtp encryption
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''MAIL_SMTP_ENCRYPTION'','
      line: "define('MAIL_SMTP_ENCRYPTION', 'tls');"

  - name: set smtp username
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''MAIL_SMTP_USERNAME'','
      line: "define('MAIL_SMTP_USERNAME', '{{mail_username}}' );"

  - name: set smtp password
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/kanboard/config.php"
      regexp: '^define\(''MAIL_SMTP_PASSWORD'','
      line: "define('MAIL_SMTP_PASSWORD', '{{mail_password}}' );"

  ######################################################
  ## initialise the database
  ######################################################
  - name: force creation of database
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: './cli db:migrate || exit -1'
    args:
      chdir: '/home/pacs/{{pac}}/users/{{user}}/kanboard'

  ######################################################
  ## activate website
  ######################################################
  - name: drop htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
       state: absent

  - name: create symbolic link for htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/kanboard"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
      state: link
